apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        livenessProbe:
          exec:
            command: 
              - sh
              - -c 
              - "redis-cli -h localhost ping"
          initialDelaySeconds: 3
          periodSeconds: 3
        requests:
          cpu: "0.15"
          memory: 256Mi
        limits:
          memory: 512Mi
          cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 6379
  selector:
    app: backend
