apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheatsheet
  labels:
    app: cheatsheet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheatsheet
template:
  metadata:
    labels:
      app: cheatsheet      
  spec:
    containers:
    - name: cheatsheet
      image: sonatconsulting/kubernetes-cheat:1.2
      ports:
      - containerPort: 80
        name: web    
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
 

        