apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cheatsheet
  labels:
    app: cheatsheet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheatsheet
  template:
    metadata:
      labels:
        app: cheatsheet      
    spec:
      containers:
      - name: cheatsheet
        image: sonatconsulting/kubernetes-cheat:1.2
        ports:
        - containerPort: 80
          name: web    
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cheatsheet
  labels:
    app: cheatsheet
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: cheatsheet