apiVersion: v1
kind: Pod
metadata:
  name: cheatsheet
spec:
  containers:
  - name: cheatsheeet
    image: sonatconsulting/kubernetes-cheat:0.8
    ports:
      - containerPort: 80
        name: web    
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3

        
 

        